# Generated by Django 3.2.4 on 2021-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='lat',
            field=models.FloatField(default=17.41710876415962),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='long',
            field=models.FloatField(default=78.44529794540337),
        ),
    ]
